add work with footer, intents, notifications
magsdk/boilerplate pull request #2
Opened 2018-08-27 15:21 UTC by Harryk13

patch or major version

2018-08-27 16:05 UTC, DarkPark requested changes
eslint ошибки тоже надо все исправить

2018-08-27 16:05 UTC, DarkPark commented on .eslintrc.js
> +    extends: require.resolve('mag-eslint-config/.eslintrc.js')
тут уже было как надо

2018-08-27 16:05 UTC, DarkPark commented on app/develop.html
> +        <script type="text/javascript" src="http://10.110.2.16:8000/target/target-script-min.js#harry"></script>
это лишнее

2018-08-27 16:05 UTC, DarkPark commented on package.json
> +        "mag-eslint-config": "^1.0.0",
правильный тут только один пакет - mag-eslint

2018-08-27 16:05 UTC, DarkPark commented on package.json
>          "mag-component-footer": "2.*.*",
лучше без *

2018-08-27 16:05 UTC, DarkPark commented on package.json
> +        "resource": "audio"
audio?

2018-08-27 16:05 UTC, DarkPark commented on src/js/modules/text.js
> +module.exports = 'Extremity direction existence as dashwoods do up. Securing marianne led welcomed offended' +
лучше бы через `['...', '...', '...'].join()`

2018-08-27 16:05 UTC, DarkPark commented on src/sass/vars/1080.scss
> +$safePadding: 		20px * 1.5;
хорошо бы подравнять все отступы
(и тут и в других разрешениях)

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +    Scroll         = require('stb-component-scrollbar'),
лучше ScrollBar

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +
желательно две пустые строки

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +    panelSet, mainPanel, footer,
этот блок переменных без значений должен быть в самом конце

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +    var intent;
нет смысла тут разделять декларацию и использование переменной

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +            debug.fail('Play error', error);
модуль debug под вопросом
возможно лучше использовать консоль

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +modalRadio = new ModalMessage({
желательно отступить

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +                _('Show')
если используется локализация то и .po файлы надо сгенерировать

2018-08-27 16:05 UTC, DarkPark commented on src/js/pages/main.js
> +                url: '',
нужны реальные ссылки
например, http://movietrailers.apple.com/movies/independent/indivisible/indivisible-trailer-1_h1080p.mov
брать можно кучу тут - http://www.hd-trailers.net/

2018-08-28 08:08 UTC, Harryk13 commented on src/js/pages/main.js
> +    Scroll         = require('stb-component-scrollbar'),
У нас нет компонента stb-component-scroll-bar

2018-08-28 08:09 UTC, Harryk13 commented on src/js/pages/main.js
> +    panelSet, mainPanel, footer,
он не может быть в конце, далее эти переменные используються при объявлении

2018-08-28 08:09 UTC, Harryk13 commented on src/js/pages/main.js
> +    var intent;
+

2018-08-28 08:09 UTC, Harryk13 commented on src/js/pages/main.js
> +            debug.fail('Play error', error);
ок

2018-08-28 08:10 UTC, Harryk13 commented on src/js/pages/main.js
> +                url: '',
ок

2018-08-28 08:16 UTC, Harryk13 commented on package.json
>          "mag-component-footer": "2.*.*",
ок

2018-08-28 08:16 UTC, Harryk13 commented on package.json
> +        "resource": "audio"
это поле лишнее, удалил

2018-08-28 08:17 UTC, Harryk13 commented on src/js/modules/text.js
> +module.exports = 'Extremity direction existence as dashwoods do up. Securing marianne led welcomed offended' +
так нагляднее и так автоматически делает среда разработки

2018-08-28 08:30 UTC, Harryk13 commented on package.json
> +        "mag-eslint-config": "^1.0.0",
ok

2018-08-28 08:30 UTC, Harryk13 commented on app/develop.html
> +        <script type="text/javascript" src="http://10.110.2.16:8000/target/target-script-min.js#harry"></script>
ok

2018-08-28 08:31 UTC, Harryk13 commented on .eslintrc.js
> +    extends: require.resolve('mag-eslint-config/.eslintrc.js')
ok

2018-08-29 07:55 UTC, Harryk13 commented on src/js/pages/main.js
> +                _('Show')
ок

2018-09-07 10:26 UTC, merged